services:
  api:
    build: api/.
    working_dir: /var/www
    volumes:
      - ./api:/var/www
      - storage_data:/var/www/storage
      - cache_data:/var/www/bootstrap/cache
    command: php-fpm
    depends_on:
      - database

  api-nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www
      - ./api/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  nlp_service:
    build: nlp_service/.
    volumes:
      - ./nlp_service:/app
    ports:
      - "5000:5000"

volumes:
  database_data:
  storage_data:
  cache_data:
  redis_data:
